gotson/komga

- komga-webui/src/views/BookReader.vue
This changes the menu buttons in the reader overlay to change to a column when on screens smaller than the md breakpoint.
It's a useful change as the buttons are often off the screen and cannot be pressed on devices as small as phones.
> fix(webui): make overlay buttons more responsive on smaller screens

- komga-webui/src/functions/meta-utilities.ts
- komga-webui/src/router.ts
- komga-webui/src/views/BookReader.vue
- komga-webui/src/views/BrowseBook.vue
- komga-webui/src/views/BrowseSeries.vue
This is simple aesthetic change that puts series - book title in the to the reader overlay and the browser tab title. 
Sometimes I had multiple book tabs open and had to go through each to find the right one, so I think this is at least a little useful.
Let me know what you think.
Example:
> feat(webui): add the series and book title to the reader overlay and page title

- komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/comicinfo/ComicInfoProvider.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/comicinfo/dto/AgeRating.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/comicinfo/dto/ComicInfo.kt
- komga/src/test/kotlin/org/gotson/komga/infrastructure/metadata/comicinfo/dto/ComicInfoTest.kt
- komga/src/test/resources/comicinfo/ComicInfo2.xml
[ComicTagger](https://github.com/comictagger/comictagger) uses the `Day` tag for the publishing day, and "MA15+" instead of "MA 15+" for the age rating, which Komga currently ignores.
> fix(metadata): recognize ComicInfo Day tag and "MA15+" rating

- komga-webui/src/components/HorizontalScroller.vue
Fix 1: Computing the scrollability on mount makes sure that the right chevron is not clickable when it's not possible to scroll after page load.
Fix 2: `container.scrollLeft` may return a decimal value on systems using display scaling. I discovered this issue while scrolling through Komga on my work laptop (using 125%). By rounding the value the `canScrollRight` equation will always return false if the div was already scrolled to the rightmost position.
> fix(webui): compute scrollability on mount, fix right chevron when using display scaling

- komga/src/main/kotlin/org/gotson/komga/interfaces/rest/BookController.kt
API is documented as supporting `accept: image/*` in the HTTP request,
but doing so results in server response with the status 406.
This commit updates the `GetMapping` annotation to correctly support
these values in the HTTP `accept` header.
As said in the issue, this fix currently the following test: `BookControllerTest > HttpCache > given request with If-Modified-Since headers when getting page then returns 304 not modified()`
closes #350
> fix(api): support accept header in getBookPage

- komga-webui/src/styles/global.css
This PR solves the problem with the vertical scrollbar always showing.  As per my comment on the ticket,
This is the expected behavior of the Vuetify package that normalizes the display.  However this particular behaviour is hotly debated ( [See here](https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#scrollbar-overflow) ) but i agree it would be nice to have it only show when needed as that is what users have come to expect these days.
Tested this across Chrome and Firefox with a variety of screen sizes and works as expected
> fix(webui) Only show the vertical scrollbar when required.

- komga/src/main/kotlin/org/gotson/komga/interfaces/rest/BookController.kt
- komga/src/main/kotlin/org/gotson/komga/interfaces/rest/SeriesController.kt
This adds a small description to `read-progress` endpoint for series and books to make it more clear what they do
> Add small description for read-progress

- komga-webui/src/locales/en.json
- komga-webui/src/views/BookReader.vue
This PR adds a gray option for the background of the webreader, instead of just black and white. It uses the gray color from the dark webui theme.
> feat: added gray backround option to book reader

- komga-webui/src/components/DropZone.vue
- komga-webui/src/components/dialogs/EditSeriesDialog.vue
fix some issues with custom cover uploads:
- new cover was not being selected after upload if there was already an uploaded cover 
- unable to upload the same file after canceling or finishing upload (tested in chrome)
- when uploading multiple covers last file would be skipped
> fix(webui): series cover uploads

- DEVELOPING.md
- komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/PdfExtractor.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/ZipExtractor.kt
`removalListener` executes asynchronously (after eviction), but `evictionListener` executes synchronously during eviction, so the object can still be acted on and closed properly.
https://github.com/ben-manes/caffeine/wiki/Removal
https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Caffeine.html#evictionListener(com.github.benmanes.caffeine.cache.RemovalListener)
In addition, fixed some wording in the dev document to save someone else the frustration of wondering why it seemed a package was missing while committing
> Fix PDDocument not getting closed before cache eviction

- komga-webui/src/components/ItemCard.vue
This adds the HTML title attribute on the book/series titles in the ItemCards, so that when you hover over it with the mouse, the full title will show in a popup. This helps with series with long titles that do not fit on the cards.
Fixes #836
Examples:
> fix(webui): show the full title of book/series on hover in cards

- komga-webui/src/functions/file.ts
- komga-webui/src/functions/resize-image.ts
- komga-webui/src/locales/en.json
- komga-webui/src/views/BookReader.vue
This adds two buttons to the overflow menu of the reader to set the current page as the poster for either the book or series. To avoid large posters, it will also try to resize the image to max. 500x500 pixels before setting it as the poster.
Fixes #838 
Example of the buttons:
Hopefully the code quality is good enough, my TypeScript knowledge is not very good! Otherwise I'd be glad to improve it if you have advice.
> feat(webui): set the currently viewed page as poster for book/series

- komga-webui/src/views/BrowseSeries.vue
this is the same fix as d343740f3021686bae9a41fd73c2102a51239faa, but applied to the series view instead of an individual book.
if the first issue of a series was released on January 1 applying a negative timezone offset will display the previous year.
> fix(webui): display release date without timezone adjustment

- komga/src/main/kotlin/org/gotson/komga/interfaces/api/rest/ReadListController.kt
- komga/src/main/kotlin/org/gotson/komga/interfaces/api/rest/SeriesController.kt
fixes an issue with series or read list archives that contain an entry over 4GB
At this point every archiver should support zip64 so it should be fine to always use it
> fix: use zip64 for archive downloads

- komga/src/main/kotlin/org/gotson/komga/infrastructure/web/EtagFilterConfiguration.kt
- komga/src/main/kotlin/org/gotson/komga/interfaces/api/rest/BookController.kt
- Disable ETag filter for file downloads
- Return content length header for book downloads
> fix: content length header for book downloads

- .github/workflows/ci.yml
- ci/publish-dockerhub.sh
- komga/Dockerfile
- komga/Dockerfile.legacy
Some people prefer to pull containers from GHCR so I've setup the CI/CD to do that.
Whilst at it I added the source label to the containers so that tools like Renovate can find the source for release notes.
If you'd prefer this work as two seperate MRs & commits I'm happy to split them up.
> Push container to GHCR & set source label on container

- komga/src/main/kotlin/org/gotson/komga/infrastructure/jooq/main/BookDao.kt
When I'm reading a volume from a series I expect the cover of the volume I'm currently reading to be shown in my library when I have the "first unread or X" setting on, rather than the *next* volume, after the one I'm currently reading.
I realize that the setting mentions "unread" so it might be a little confusing but I felt like adding yet another setting would be even more confusing and I personally have a hard time imagining when one would want to see the next volume cover but maybe I'm missing something out :)
> fix(api): first unread cover should include in progress books

- komga/build.gradle.kts
- komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/divina/ZipExtractor.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/epub/Epub.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/epub/EpubExtractor.kt
- komga/src/main/kotlin/org/gotson/komga/infrastructure/util/ZipFileUtils.kt
Currently ZipFile read will scan entire file to read each entry's local file header on each request for book page image.
This can be quite a slow operation depending on archive file size. In my tests 800mb archive with ~400 entries stored on hdd takes ~3 seconds on initial read on Linux system.
After initial read OS will cache file and subsequent reads become really fast ~50-100ms, but in my opinion it's better to not rely on OS for caching
If we only read central directory header entry retrieval takes ~100-150ms instead of 3 seconds which is about 30 times faster
The downside to only reading central directory is that filename can use Unicode extra field and that field is (for some reason) only added to local file header.
In that case retrieving entry might fail and we fallback to …
> perf: faster zip entry extraction

- komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/epub/EpubMetadataProvider.kt
- komga/src/test/kotlin/org/gotson/komga/infrastructure/metadata/epub/EpubMetadataProviderTest.kt
- komga/src/test/resources/epub/Panik im Paradies.opf
> feat(metadata): use group-position for epub series index

- CONTRIBUTING.md
The FAQ link is broken currently. This pull request simply changes the URL from https://komga.org/faq/ to https://komga.org/docs/faq/
> docs: fix FAQ link in CONTRIBUTING.md
